name: Vote CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'vote/**'
      - '.github/workflows/build-vote.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=rsathyavani
            -Dsonar.projectKey=rsathyavani_votingapp-vote
            -Dsonar.sources=vote
            
      - name: Login to Docker Hub
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7.1.0
        with:
          context: ./vote
          file: vote/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/votingapp-vote:${{ github.run_number }}

      - name: Update image tag
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/votingapp-vote:${{ github.run_number }}|g' k8s-specifications/vote-deployment.yaml
          git add k8s-specifications/vote-deployment.yaml
          git commit -m "update image tag" && git push
