name: Worker CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yml'

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build_sonarscan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore worker/Worker.csproj

      - name: Begin SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"votingapp-worker" \
            /o:"rsathyavani" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.qualitygate.wait=true
            
      - name: Build
        run: |
          dotnet build worker/Worker.csproj \
            --no-restore \
            --configuration Release

      - name: End SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner end \
            /d:sonar.login="$SONAR_TOKEN"
  
  dockerbuildandpush:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7.1.0
        with:
          context: ./worker
          file: worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/votingapp-worker:${{ github.run_number }}

      - name: Update image tag
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/votingapp-worker:${{ github.run_number }}|g' k8s-specifications/worker-deployment.yaml
          git add k8s-specifications/worker-deployment.yaml
          git commit -m "update image tag" && git push
